name: opendialog-core
services:
  php-service:
    type: php:7.3
    via: cli
    webroot: .
    xdebug: true
    config:
      php: config/php.ini
  dgraph-zero:
    type: compose
    services:
      image: dgraph/dgraph:v1.1.0
      restart: on-failure
      command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    type: compose
    services:
      image: dgraph/dgraph:v1.1.0
      restart: on-failure
      command: dgraph alpha --my=dgraph-alpha:7080 --lru_mb=2048 --zero=dgraph-zero:5080
tooling:
  test:
    service: php-service
    description: Runs all tests
    cmd: php /app/vendor/bin/phpunit
